import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { Section } from "@/components/ui/section";
import { Reveal } from "@/components/ui/reveal";
import { SectionHeading } from "@/components/ui/section-heading";
import { featuredCaseStudies } from "@/lib/data/case-studies";

const paletteClass = { lime: "bg-lime-100", steel: "bg-slate-200", sand: "bg-stone-200" } as const;
export function Work() { return <Section id="work" bordered tone="raised"><SectionHeading kicker="Selected work" title={<>See why clients trust <em className="font-normal text-primary">Evalunor.</em></>} description="Hover a card to scroll the build. Click through for the full search story." /><div className="mt-12 grid gap-5 lg:grid-cols-3">{featuredCaseStudies.map((study, index) => <Reveal key={study.slug} delay={index * 70}><Link href={`/case-studies/${study.slug}`} className="group block overflow-hidden rounded-lg border border-border bg-background transition hover:-translate-y-1 hover:shadow-2xl"><div className={`h-72 overflow-hidden p-4 ${paletteClass[study.palette]}`}><div className="h-[630px] rounded-md bg-white p-5 shadow-sm transition-transform duration-[3500ms] ease-out group-hover:-translate-y-[350px]"><div className="mb-5 flex gap-1.5"><i className="size-2 rounded-full bg-black/15"/><i className="size-2 rounded-full bg-black/15"/><i className="size-2 rounded-full bg-black/15"/></div><p className="font-mono text-[9px] font-bold tracking-[.2em] text-slate-400">{study.client.toUpperCase()}</p><h3 className="mt-3 max-w-xs font-display text-2xl font-semibold leading-tight tracking-tight text-slate-900">{study.caption.split(".")[0]}.</h3><div className="mt-6 grid grid-cols-3 gap-2">{Array.from({ length: 9 }).map((_, boxIndex) => <i key={boxIndex} className="h-12 rounded bg-slate-900/[.06]" />)}</div><div className="mt-4 h-3 w-3/4 rounded bg-slate-900/[.07]"/><div className="mt-3 h-3 w-1/2 rounded bg-slate-900/[.07]"/></div></div><div className="p-6"><h3 className="font-display text-xl font-semibold tracking-tight">{study.client}<span className="mt-1 block font-mono text-[10px] font-medium uppercase tracking-[.13em] text-muted-foreground">{study.sector}</span></h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{study.challenge}</p><div className="mt-5 flex gap-5 border-t border-border pt-4">{study.metrics.map((metric) => <div key={metric.label}><strong className="font-display text-lg tracking-tight">{metric.value}</strong><span className="mt-1 block text-[10px] leading-tight text-muted-foreground">{metric.label}</span></div>)}</div><span className="mt-5 inline-flex items-center gap-1 text-sm font-semibold text-primary">Read the story <ArrowUpRight className="size-3.5" /></span></div></Link></Reveal>)}</div></Section>; }
