import type { Metadata } from "next";
import { Mail, ArrowRight } from "lucide-react";
import { Navbar } from "@/components/layout/navbar";
import { Footer } from "@/components/layout/footer";
import { Section } from "@/components/ui/section";
import { Button } from "@/components/ui/button";
import { site } from "@/lib/site";
export const metadata: Metadata = { title: "Contact Evalunor", description: "Request a free SEO audit from Evalunor." };
export default function ContactPage() { return <><Navbar /><main><section className="border-b border-border py-24 sm:py-32"><div className="container-page"><p className="kicker mb-5">Let’s talk</p><h1 className="display max-w-4xl text-[clamp(3rem,7vw,6.5rem)]">Tell us where you should be <em className="font-normal text-primary">ranking.</em></h1><p className="mt-8 max-w-2xl text-lg leading-relaxed text-muted-foreground">Send the site and terms you care about. We will send back a short, blunt teardown within two business days.</p></div></section><Section><div className="grid gap-12 lg:grid-cols-[.8fr_1fr] lg:gap-24"><div><h2 className="display text-4xl">No sales theatre.<br /><em className="font-normal text-primary">Just the diagnosis.</em></h2><a href={`mailto:${site.email}`} className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-primary hover:underline"><Mail className="size-4" />{site.email}</a></div><form action="mailto:hello@evalunor.com" method="post" encType="text/plain" className="grid gap-5 rounded-lg border border-border bg-card/40 p-7"><label className="grid gap-2 text-sm font-medium">Name<input required name="name" className="h-11 rounded-md border border-input bg-background px-3 text-sm outline-none focus:border-primary" /></label><label className="grid gap-2 text-sm font-medium">Work email<input required type="email" name="email" className="h-11 rounded-md border border-input bg-background px-3 text-sm outline-none focus:border-primary" /></label><label className="grid gap-2 text-sm font-medium">Website<input type="url" name="website" placeholder="https://" className="h-11 rounded-md border border-input bg-background px-3 text-sm outline-none focus:border-primary" /></label><label className="grid gap-2 text-sm font-medium">What are you trying to rank for?<textarea name="message" rows={5} className="resize-y rounded-md border border-input bg-background px-3 py-3 text-sm outline-none focus:border-primary" /></label><Button type="submit" size="lg">Request my teardown <ArrowRight className="size-4" /></Button><p className="text-xs text-muted-foreground">This opens your email client. Connect a form endpoint before launch for automatic lead capture.</p></form></div></Section></main><Footer /></>; }
